apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: h0q7o1sd9-nodejs 
  janus-idp.io/tekton: h0q7o1sd9-nodejs
  backstage.io/kubernetes-id: h0q7o1sd9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h0q7o1sd9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml